apiVersion: batch/v1
kind: Job
metadata:
  name: producer
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: producer
          image: pratikshadhavane/agentic-ticket-triage-producer:v2
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"